language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-backbone-multipage' ]; then cd .. && eval "mv $currentfolder generator-backbone-multipage" && cd generator-backbone-multipage; fi

